# Generated by Django 6.0.1 on 2026-01-30 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_equipment', models.IntegerField()),
                ('avg_flowrate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_pressure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_temperature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_distribution', models.JSONField()),
            ],
            options={
                'ordering': ['-upload_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('flowrate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='analytics.dataset')),
            ],
        ),
    ]
